### ISSUE TITLE
Trouble Installing Specific ROS Dependencies Listed in requirements.txt

### ISSUE THREAD

**Issue by Dhshudjdhdh** [bhushanap/captomate#1]
Hi there,

I'm a bit of a newbie, but I'm trying to set up Captomate on an Ubuntu 22.04 system. I've run into issues installing some of the ROS-related dependencies listed in requirements.txt, specifically those with particular version numbers like action-msgs==1.2.1 and ament-* packages. These seem to not be available via pip or through standard ROS Noetic apt packages, and I’ve had trouble finding the correct versions or workarounds.

Here's what I've tried so far:

Attempted to install the packages via pip, which resulted in errors.
Tried using apt-get to install ROS packages, but some were not found.
Looked into using rosdep for installation, but ran into some configuration issues.
Any guidance on how to properly install these specific dependencies, or if there are alternative approaches for setting up the environment, would be greatly appreciated.

Thanks for your help, and apologies if I'm missing something basic!

**Comment by civtibo** [comment]
Hi there!

I might have uploaded the wrong requirements file. I have uploaded the new files. Please check again and let me know if you encounter any issues.

**Comment by Dhshudjdhdh** [comment]
Oh great 😃 the new requirements file looks much more friendly, thanks!
This project looks exactly like what I was looking for, thanks for sharing!
😊

**Comment by civtibo** [comment]
> This project looks exactly like what I was looking for, thanks for sharing!

Glad to be of help!

Assuming the requirements file worked, I am closing this discussion. Feel free to post any issues you encounter with the installation.

**Comment by Dhshudjdhdh** [comment]
I didn't have a chance to test it yet because I started working on another
part of my project, but I will be looking into it again in the coming weeks
and I will let you know. Hopefully it will work this way. Once again, thank
you very much. I will keep you updated if it works. 😎👍
